from django.urls import path
from AppCoder import views

urlpatterns = [
    path("", views.inicio, name='Inicio'),
    path("edificios/", views.edificios, name='Edificios'),
    path('equipo/', views.equipo, name="Equipo"),
    path('edificiosApi/', views.edificiosapi),
    path('equipoApi/', views.equipoapi),
    path('encargados/', views.encargados, name="Encargados"),
    path('encargadoApi/', views.encargadoapi),
    path("busquedaEdificio/", views.buscaredificio, name="BusquedaEdificio"),
    path("buscar/", views.buscar),
    path("leerEdificio/", views.leer_edificio),
    path("crearEdificio/", views.crear_edificio),
    path("editarEdificio/", views.editar_edificio),
    path("eliminarEdificio/", views.eliminar_edificio),
    path("edificio/list/", views.EdificioList.as_view(), name='List'),
    path("edificio/create/", views.EdificioCreate.as_view(), name='New'),
    path("edificio/edit/<pk>", views.EdificioEdit.as_view(), name='Edit'),
    path("edificio/detail/<pk>", views.EdificioDetail.as_view(), name='Detail'),
    path("edificio/delete/<pk>", views.EdificioDelete.as_view(), name='Delete'),
    path("equipo/list/", views.EquipoList.as_view(), name='ListTeam'),
    path("equipo/create/", views.EquipoCreate.as_view(), name='NewTeam'),
    path("equipo/edit/<pk>", views.EquipoEdit.as_view(), name='EditTeam'),
    path("equipo/detail/<pk>", views.EquipoDetail.as_view(), name='DetailTeam'),
    path("equipo/delete/<pk>", views.EquipoDelete.as_view(), name='DeleteTeam'),
    path("encargado/list/", views.EncargadoList.as_view(), name='ListEnc'),
    path("encargado/create/", views.EncargadoCreate.as_view(), name='NewEnc'),
    path("encargado/edit/<pk>", views.EncargadoEdit.as_view(), name='EditEnc'),
    path("encargado/detail/<pk>", views.EncargadoDetail.as_view(), name='DetailEnc'),
    path("encargado/delete/<pk>", views.EncargadoDelete.as_view(), name='DeleteEnc'),
    path("busquedaEquipo/", views.buscarEquipo, name="BusquedaEquipo"),
    path("buscarequi/", views.buscarequi),
    path("busquedaEncargado/", views.buscarEncargado, name="BusquedaEncargado"),
    path("buscarenc/", views.buscarenc),
]
