# Generated by Django 4.1.3 on 2022-11-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fantasia', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
