# Generated by Django 4.1.3 on 2022-11-29 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_encargado_expensa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargado',
            name='direccion',
        ),
    ]
