# Generated by Django 4.1.3 on 2022-11-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_remove_encargado_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargado',
            old_name='nombre_fantasia',
            new_name='nombre',
        ),
    ]
