# Generated by Django 4.1.3 on 2022-11-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='num_contacto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
