# Generated by Django 4.1.3 on 2022-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_equipo_mail_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargado',
            name='mail_contacto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encargado',
            name='num_contacto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
