# Generated by Django 4.1.3 on 2022-11-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_encargado_mail_contacto_encargado_num_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='mail_contacto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
