# Generated by Django 4.1.3 on 2022-12-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_rename_nombre_encargado_nombre_enc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expensa',
        ),
    ]
